# Generated by Django 4.2.13 on 2024-07-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
