# Generated by Django 4.2.13 on 2024-07-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='theme',
            field=models.CharField(default='beige', max_length=100),
        ),
    ]
