# Generated by Django 4.2.13 on 2024-07-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='short_description',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
