# Generated by Django 4.2.13 on 2024-07-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_story_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sort_option',
            field=models.CharField(default='alphabetical', max_length=20),
        ),
    ]
