# Generated by Django 4.2.13 on 2024-07-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_story_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='theme',
            field=models.CharField(max_length=100),
        ),
    ]
