# Generated by Django 4.2.13 on 2024-07-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_story_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, default='About story...', max_length=5000),
        ),
    ]
