# Generated by Django 4.2.13 on 2024-07-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chapter_position_alter_story_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercard',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
