# Generated by Django 4.2.13 on 2024-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_charactercard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/banners'),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='group',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
