# Generated by Django 4.2.13 on 2024-07-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_story_banner_alter_charactercard_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='about',
            new_name='description',
        ),
    ]
